config:
  name: order-configmap
  port: 9000
  database: postgresql
  ddl: create
  driver: org.postgresql.Driver
secret:
    name: order-secret
deployment:
  app:
    name: order
    type: NodePort
    image: andrey1andrey/order-service:1.0
    port: 9000
    sport: "9000"
    replicas: 1
    uri: "order-service"
    jwtsecret: secret
  db:
    name: order-postgresql
    type: NodePort
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: order
    type: NodePort
    protocol: TCP
    port: 9000
  db:
    name: order-postgresql
    type: NodePort
    dbname: db
    host: "order-postgresql"
    port: 5432
    sport: "5432"